### ISSUE TITLE
Add Placed and Expired states to the Promotion model

### ISSUE THREAD

**Issue by ahbbzong** [NYU-Devops2021-Promotion/promotions#27]
**As a team member** ...  
**I need to add Placed and Expired states to the Promotion model** ...  
**So that we can change states of an object** ...  

**Details & Assumptions:** 
*  Add states to the Promotion model

**Acceptance Criteria:**

```gherkin
Given states of Promotion model 
When it is merged by pull requests
Then it can allow its functions to change its states
```

**Comment by HerlinHe** [comment]
As discussed, the "cancel promotion" can be implemented without modifying the model.
