### ISSUE TITLE
Make sure 95%+ code coverage

### ISSUE THREAD

**Issue by ahbbzong** [NYU-Devops2021-Promotion/promotions#31]
**As a tester ...  
**I need to make sure the reliability of code...  
**So that I need make sure the code coverage is above 95%

**Details & Assumptions:** 
Run the nosestests to check the coverage 

**Acceptance Criteria:**
Make the coverage 95%+

```gherkin
Given a completed code
When run the nosetests
Then make sure the coverage is 95%+ and no error.
```

**Comment by HerlinHe** [comment]
Is it necessary to set this as an independent issue? Why not require every teammate to test their work before the pull request and make sure the coverage >= 95%?
