### ISSUE TITLE
Configure Travis CI to run test cases

### ISSUE THREAD

**Issue by ReedyChen** [NYU-Devops2021-Promotion/promotions#33]
**As a team member** ...  
**I need to configure Travis CI** ...  
**So that test cases can be run** ...  

**Details & Assumptions:** 
* Configure Travis CI to run test cases

**Acceptance Criteria:**

```gherkin
Given Travis CI 
When someone configures it
Then we can let Travis CI to run test cases
```

**Comment by HerlinHe** [comment]
Same as #32
