### ISSUE TITLE
RESTful query with more than one attribute

### ISSUE THREAD

**Issue by HerlinHe** [NYU-Devops2021-Promotion/promotions#36]
**As a** Customer
**I need** to see all available promotions for a product
**So that** I can make a decision of purchasing

**Details & Assumptions:** 
* Since customers care about the product, we need to implement query function for product_id, and as a REST API, we need to implement multi-attribute query, like "promotions/<int: product_id>/from_data/<data>", "promotions/<int: product_id>/to_date/<data>" or a more useful one "promotions/<int: product_id>/is_available/<bool>"

**Acceptance Criteria:**

```gherkin
Given a customer
When he/she wants to check the available promotions for a product
Then the right query result can be shown
```

**Comment by ahbbzong** [comment]
I implemented this one, just check my pull request

**Comment by HerlinHe** [comment]
Yeah, I read your last implementation. That is a list query for one attribute, and I set up this issue because I want to query for more than one attribute. This requires modifications on both model and routes files.
